project:
  type: website

website:
  title: "Aaron Mackay"
  site-url: https://amackay.netlify.app/
  description: "Data Science Blog by me... Aaron"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/ajmackay
format:
  html:
    theme: cosmo
    css: styles.css # change to theme.scss when ready to play with css

editor: visual

