project:
  type: website

website:
  title: "I Can Do Hard Things"
  site-url: https://amackay.netlify.app/
  description: "A blog where I try and do things that smart people do"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/ajmackay
format:
  html:
    theme: cosmo
    css: styles.css # change to theme.scss when ready to play with css

editor: visual

